/** Declaration file generated by dts-gen */

export const simpleMethods: string[];

export const simpleRequestHeaders: string[];

export const simpleResponseHeaders: string[];

export function create(options: any): any;

