/** Declaration file generated by dts-gen */

export = wikibase_edit;

declare type RequestFn = (params: any, reqConfig?: any) => Promise<any>;

declare type WikibaseEditAPI = {
  label: {
    set: RequestFn;
  };
  description: {
    set: RequestFn;
  };
  alias: {
    set: RequestFn;
    add: RequestFn;
    remove: RequestFn;
  };
  claim: {
    set: RequestFn;
    remove: RequestFn;
    // Bundled
    create: RequestFn;
    update: RequestFn;
    move: RequestFn;
  };
  qualifier: {
    set: RequestFn;
    remove: RequestFn;
    // Bundled
    update: RequestFn;
    move: RequestFn;
  };
  reference: {
    set: RequestFn;
    remove: RequestFn;
  };
  entity: {
    create: RequestFn;
    edit: RequestFn;
    merge: RequestFn;
    delete: RequestFn;
  };
  sitelink: {
    set: RequestFn;
  };
  badge: {
    // Bundled
    add: RequestFn;
    remove: RequestFn;
  };
};

declare function wikibase_edit(generalConfig: any): WikibaseEditAPI;
