import openapiTS, { astToString } from 'openapi-typescript';
import { setTimeout } from 'node:timers/promises';
import { EndToEndServer } from './e2e-server';
import { parseArgs } from 'node:util';
import { join } from 'node:path';

const { values } = parseArgs({
  args: Bun.argv,
  allowPositionals: true,
  strict: true,
  options: {
    outdir: {
      type: 'string',
    },
    onlyTs: {
      type: 'boolean',
    },
  },
});

const outDir = values.outdir || './e2e-out';

EndToEndServer.listen(45765);

const getSpec = async () =>
  await Bun.fetch('http://localhost:45765/server/openapi/json')
    .then(res => res.json())
    .catch(() => undefined);

let spec = await getSpec();
while (!spec) {
  console.log('OpenAPI spec not available yet, retrying in 1 seconds...');
  await setTimeout(1000);
  spec = await getSpec();
}

if (!values.onlyTs)
  await Bun.write(join(outDir, 'openapi-spec.json'), JSON.stringify(spec, null, 2));

const ast = await openapiTS(spec, {
  exportType: true,
  enum: false,
  enumValues: false,
  makePathsEnum: true,
  dedupeEnums: true,
}).catch(err => {
  console.error('Error generating TypeScript types from OpenAPI spec:', err);
  process.exit(1);
});
const contents = astToString(ast);

await Bun.write(join(outDir, 'openapi-server-types.ts'), contents);

const HELPERS_FILE = `/**
 * AUTO-GENERATED by src/e2e-generator.ts — DO NOT EDIT.
 * Source of truth: https://github.com/Kompakkt/Server/blob/main/src/e2e-generator.ts
 * Regenerate with: bun run generate:openapi
 */
import type { paths, operations, ApiPaths, components } from './openapi-server-types';

export type { paths, operations, ApiPaths, components };

export type HttpMethod =
  | 'get' | 'post' | 'put' | 'delete'
  | 'patch' | 'options' | 'head' | 'trace';

export type ContentType =
  | 'application/json'
  | 'multipart/form-data'
  | 'application/x-www-form-urlencoded'
  | 'text/plain';

export type Endpoint<M extends HttpMethod, P extends keyof paths> =
  paths[P][M] extends never ? never : paths[P][M];

type Empty = Record<string, never>;

type _ExtractProp<T, K extends string> = K extends keyof T ? T[K] : never;
type _Normalize<T> = [T] extends [Empty] ? Empty : [T] extends [never] ? Empty : T;
type _Get<E, K extends string> =
  E extends { parameters: infer P }
    ? [P] extends [Empty]
      ? Empty
      : _Normalize<NonNullable<_ExtractProp<P, K>>>
    : Empty;
type _PathParams<E>   = _Get<E, 'path'>;
type _QueryParams<E>  = _Get<E, 'query'>;
type _HeaderParams<E> = _Get<E, 'header'>;
type _CookieParams<E> = _Get<E, 'cookie'>;

export type PathParams<E>   = _PathParams<E>;
export type QueryParams<E>  = _QueryParams<E>;
export type HeaderParams<E> = _HeaderParams<E>;
export type CookieParams<E> = _CookieParams<E>;

export type RequestBody<E, CT extends ContentType = 'application/json'> =
  E extends { requestBody: { content: { [K in CT]: infer B } } } ? B : never;

export type Response<
  E,
  S  extends number     = 200,
  CT extends ContentType = 'application/json'
> = E extends { responses: infer R }
  ? R extends Record<S, infer V>
    ? V extends { content: { [K in CT]: infer B } } ? B : never
    : never
  : never;

export type Responses<E> = E extends { responses: infer R } ? R : never;

type RouteEntry<P extends keyof paths, M extends HttpMethod> = {
  method:     M;
  path:       P;
  pathParams: _PathParams<paths[P][M]>;
  query:      _QueryParams<paths[P][M]>;
  headers:    _HeaderParams<paths[P][M]>;
  cookies:    _CookieParams<paths[P][M]>;
  body:       RequestBody<paths[P][M]>;
  response:   Response<paths[P][M]>;
  responses:  Responses<paths[P][M]>;
};

export type Routes = {
  [P in keyof paths]: {
    [M in keyof paths[P]]: paths[P][M] extends never
      ? never
      : M extends HttpMethod ? RouteEntry<P, M> : never;
  }[keyof paths[P]];
}[keyof paths];

type _UnionToIntersection<U> =
  (U extends any ? (x: U) => void : never) extends (x: infer I) => void ? I : never;

type _RouteByKey<R> = R extends { method: infer M; path: infer P }
  ? { [K in \`\${Extract<M, string>} \${Extract<P, string>}\`]: R }
  : never;

export type RoutesByKey = _UnionToIntersection<_RouteByKey<Routes>>;
`;

if (!values.onlyTs) await Bun.write(join(outDir, 'kompakkt-api-helpers.ts'), HELPERS_FILE);

await EndToEndServer.stop();

await setTimeout(1000);

process.exit(0);
