import Elysia from 'elysia';
import { openapi } from '@elysiajs/openapi';
import openapiTS, { astToString } from 'openapi-typescript';
import { setTimeout } from 'node:timers/promises';
import type { AnyElysia } from './plugins/plugin-controller';
import finalServer from './server.final';
import { RouterTagsAsTagObjects } from './routers/tags';
import cologneCaveRouter from './plugins/cologne-cave/router';
import dfgMetsRouter from './plugins/dfg-mets/router';
import oidcRouter from './plugins/oidc/router';
import sketchfabImportRouter from './plugins/sketchfab-importer/router';
import ssoNFDI4CultureRouter from './plugins/sso-nfdi4culture/router';
import wikibaseRouter from './plugins/wikibase/router';

let app: AnyElysia = new Elysia();

const routers: AnyElysia[] = [
  cologneCaveRouter,
  dfgMetsRouter,
  oidcRouter,
  sketchfabImportRouter,
  ssoNFDI4CultureRouter,
  wikibaseRouter,
];

for (const router of routers) {
  app = app.use(router);
}

const final = new Elysia({
  prefix: '/server',
  serve: {
    // 4096MB
    maxRequestBodySize: 4096 * 1024 * 1024,
    // Long timeout
    idleTimeout: 255,
  },
})
  .use(app)
  .use(finalServer)
  .use(
    openapi({
      documentation: {
        info: {
          title: 'Kompakkt API Documentation',
          version: '2.0.0',
        },
        tags: RouterTagsAsTagObjects,
      },
    }),
  );

final.listen(45765);

const OpenAPISpec = await Bun.fetch('http://localhost:45765/server/openapi/json').then(res =>
  res.json(),
);
const ast = await openapiTS(OpenAPISpec, {
  exportType: true,
  enum: true,
  makePathsEnum: true,
});
const contents = astToString(ast);

await Bun.write('./e2e-out/openapi-server-types.ts', contents);

const HELPERS_FILE = `/**
 * AUTO-GENERATED by src/e2e-generator.ts — DO NOT EDIT.
 * Source of truth: https://github.com/Kompakkt/Server/blob/main/src/e2e-generator.ts
 * Regenerate with: bun run generate:openapi
 */
import type { paths, operations, ApiPaths, components } from './openapi-server-types';

export type { paths, operations, ApiPaths, components };

export type HttpMethod =
  | 'get' | 'post' | 'put' | 'delete'
  | 'patch' | 'options' | 'head' | 'trace';

export type ContentType =
  | 'application/json'
  | 'multipart/form-data'
  | 'application/x-www-form-urlencoded'
  | 'text/plain';

export type Endpoint<M extends HttpMethod, P extends keyof paths> =
  paths[P][M] extends never ? never : paths[P][M];

type Empty = Record<string, never>;

type _PathParams<E>   = E extends { parameters: { path:   infer P } } ? (P extends Empty ? Empty : P) : Empty;
type _QueryParams<E>  = E extends { parameters: { query:  infer Q } } ? (Q extends Empty ? Empty : Q) : Empty;
type _HeaderParams<E> = E extends { parameters: { header: infer H } } ? (H extends Empty ? Empty : H) : Empty;
type _CookieParams<E> = E extends { parameters: { cookie: infer C } } ? (C extends Empty ? Empty : C) : Empty;

export type PathParams<E>   = _PathParams<E>;
export type QueryParams<E>  = _QueryParams<E>;
export type HeaderParams<E> = _HeaderParams<E>;
export type CookieParams<E> = _CookieParams<E>;

export type RequestBody<E, CT extends ContentType = 'application/json'> =
  E extends { requestBody: { content: { [K in CT]: infer B } } } ? B : never;

export type Response<
  E,
  S  extends number     = 200,
  CT extends ContentType = 'application/json'
> = E extends { responses: infer R }
  ? R extends Record<S, infer V>
    ? V extends { content: { [K in CT]: infer B } } ? B : never
    : never
  : never;

export type Responses<E> = E extends { responses: infer R } ? R : never;

type RouteEntry<P extends keyof paths, M extends HttpMethod> = {
  method:     M;
  path:       P;
  pathParams: _PathParams<paths[P][M]>;
  query:      _QueryParams<paths[P][M]>;
  headers:    _HeaderParams<paths[P][M]>;
  cookies:    _CookieParams<paths[P][M]>;
  body:       RequestBody<paths[P][M]>;
  response:   Response<paths[P][M]>;
  responses:  Responses<paths[P][M]>;
};

export type Routes = {
  [P in keyof paths]: {
    [M in keyof paths[P]]: paths[P][M] extends never
      ? never
      : M extends HttpMethod ? RouteEntry<P, M> : never;
  }[keyof paths[P]];
}[keyof paths];

type _UnionToIntersection<U> =
  (U extends any ? (x: U) => void : never) extends (x: infer I) => void ? I : never;

type _RouteByKey<R> = R extends { method: infer M; path: infer P }
  ? { [K in \`\${Extract<M, string>} \${Extract<P, string>}\`]: R }
  : never;

export type RoutesByKey = _UnionToIntersection<_RouteByKey<Routes>>;
`;

await Bun.write('./e2e-out/kompakkt-api-helpers.ts', HELPERS_FILE);

await final.stop();

await setTimeout(1000);

process.exit(0);
